name: Uspevai
options:
  bundleIdPrefix: am.hrant
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    MARKETING_VERSION: 6.1.0
    CURRENT_PROJECT_VERSION: 16
    SWIFT_VERSION: 5.10
targets:
  Uspevai:
    type: application
    platform: iOS
    sources: [Uspevai]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: am.hrant.uspevai
        INFOPLIST_FILE: Uspevai/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
    preBuildScripts:
      - name: Increment build number
        script: |
          if [ "$CONFIGURATION" = "Release" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(( ${CURRENT_PROJECT_VERSION:-1} + 1 ))" "$SRCROOT/Uspevai/Info.plist"
          fi
